// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'author': string;
  'date': string;
  'favourit': string;
  'favourites_icon': string;
  'flair_text': string;
  'item': string;
  'item_header': string;
  'item_header_element': string;
  'list': string;
  'loader_by_center': string;
  'picture': string;
  'video': string;
  'video_container': string;
}
export const cssExports: CssExports;
export default cssExports;
